name: KICS Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  
jobs:
  KICS-iac-security:
    name: IAC scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run KICS Scan
      continue-on-error: true
      run: |
       sudo mkdir scan_results
       docker pull checkmarx/kics:latest
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 scan -p $GITHUB_WORKSPACE/terraform,$GITHUB_WORKSPACE/cft  --report-formats "all" -o /$GITHUB_WORKSPACE/scan_results -v
       echo "------Remediating the issue id:4a1e6b34-1008-4e61-a5f2-1f7c276f8d14"
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 remediate --include-ids "4a1e6b34-1008-4e61-a5f2-1f7c276f8d14"
    - name: Upload KICS scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always() 
      with:
       sarif_file: 'scan_results/results.sarif'
          
    - name: Archive Scan results
      uses: actions/upload-artifact@v2
      with:
       name: scan-reports
       path: scan_results   
