name: KICS Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  
jobs:
  KICS-iac-security:
    name: IAC scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: run KICS Scan
      continue-on-error: true
      run: |
       docker pull checkmarx/kics:latest
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 scan -p $GITHUB_WORKSPACE/terraform,$GITHUB_WORKSPACE/cft  --report-formats "all" -o /$GITHUB_WORKSPACE -v
       echo "Remediating id : 829ce3b8-065c-41a3-ad57-e0accfea82d2"
       docker run -u $UID:$GID -v $PWD:/$GITHUB_WORKSPACE checkmarx/kics:ubi8 remediate --include-ids "829ce3b8-065c-41a3-ad57-e0accfea82d2" --results "${GITHUB_WORKSPACE}/results.json" -v
    - name: Upload KICS scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always() 
      with:
       sarif_file: 'results.sarif'
          
    - name: Archive Scan results
      uses: actions/upload-artifact@v2
      with:
       name: scan-reports
       path: results.html   
